
package org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2014-01-06T13:27:10.934+08:00
 * Generated source version: 2.7.5
 * 
 */
public final class Service1Soap_Service1Soap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Service1");

    private Service1Soap_Service1Soap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Service1.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Service1 ss = new Service1(wsdlURL, SERVICE_NAME);
        Service1Soap port = ss.getService1Soap12();  
        
        {
            System.out.println("Invoking getSpasVisitingGuestList...");
            java.lang.String _getSpasVisitingGuestList_escort = "";
            java.lang.String _getSpasVisitingGuestList__return = port.getSpasVisitingGuestList(_getSpasVisitingGuestList_escort);
            System.out.println("getSpasVisitingGuestList.result=" + _getSpasVisitingGuestList__return);


        }

        System.exit(0);
    }

}
