package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2014-01-06T13:27:11.024+08:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "Service1Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface Service1Soap {

    @WebResult(name = "PrintPanelLabelForSSDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PrintPanelLabelForSSD", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PrintPanelLabelForSSD")
    @WebMethod(operationName = "PrintPanelLabelForSSD", action = "http://tempuri.org/PrintPanelLabelForSSD")
    @ResponseWrapper(localName = "PrintPanelLabelForSSDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PrintPanelLabelForSSDResponse")
    public java.lang.String printPanelLabelForSSD(
        @WebParam(name = "WorkOrder", targetNamespace = "http://tempuri.org/")
        java.lang.String workOrder,
        @WebParam(name = "StartPos", targetNamespace = "http://tempuri.org/")
        long startPos,
        @WebParam(name = "EndPos", targetNamespace = "http://tempuri.org/")
        long endPos,
        @WebParam(name = "PrinterName", targetNamespace = "http://tempuri.org/")
        java.lang.String printerName
    );

    @WebResult(name = "getSpasUserAttributesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getSpasUserAttributes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSpasUserAttributes")
    @WebMethod(action = "http://tempuri.org/getSpasUserAttributes")
    @ResponseWrapper(localName = "getSpasUserAttributesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSpasUserAttributesResponse")
    public java.lang.String getSpasUserAttributes(
        @WebParam(name = "BadgeID", targetNamespace = "http://tempuri.org/")
        java.lang.String badgeID
    );

    @WebResult(name = "SpasUserPasswordValidationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SpasUserPasswordValidation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SpasUserPasswordValidation")
    @WebMethod(operationName = "SpasUserPasswordValidation", action = "http://tempuri.org/SpasUserPasswordValidation")
    @ResponseWrapper(localName = "SpasUserPasswordValidationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SpasUserPasswordValidationResponse")
    public java.lang.String spasUserPasswordValidation(
        @WebParam(name = "BadgeID", targetNamespace = "http://tempuri.org/")
        java.lang.String badgeID,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        java.lang.String password
    );

    @WebResult(name = "OBALabelCheckForSSDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OBALabelCheckForSSD", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OBALabelCheckForSSD")
    @WebMethod(operationName = "OBALabelCheckForSSD", action = "http://tempuri.org/OBALabelCheckForSSD")
    @ResponseWrapper(localName = "OBALabelCheckForSSDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OBALabelCheckForSSDResponse")
    public java.lang.String obaLabelCheckForSSD(
        @WebParam(name = "ScanningString", targetNamespace = "http://tempuri.org/")
        java.lang.String scanningString,
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        java.lang.String userID,
        @WebParam(name = "LineID", targetNamespace = "http://tempuri.org/")
        java.lang.String lineID,
        @WebParam(name = "CimStepCode", targetNamespace = "http://tempuri.org/")
        java.lang.String cimStepCode
    );

    @WebResult(name = "CreateQDN_SPCResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateQDN_SPC", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateQDNSPC")
    @WebMethod(operationName = "CreateQDN_SPC", action = "http://tempuri.org/CreateQDN_SPC")
    @ResponseWrapper(localName = "CreateQDN_SPCResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateQDNSPCResponse")
    public java.lang.String createQDNSPC(
        @WebParam(name = "ThisQDN", targetNamespace = "http://tempuri.org/")
        org.tempuri.QDNAttributesSPC thisQDN
    );

    @WebResult(name = "LotReleaseResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LotRelease", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LotRelease")
    @WebMethod(operationName = "LotRelease", action = "http://tempuri.org/LotRelease")
    @ResponseWrapper(localName = "LotReleaseResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LotReleaseResponse")
    public java.lang.String lotRelease(
        @WebParam(name = "LotNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String lotNumber,
        @WebParam(name = "ReasonCode", targetNamespace = "http://tempuri.org/")
        java.lang.String reasonCode,
        @WebParam(name = "Comments", targetNamespace = "http://tempuri.org/")
        java.lang.String comments
    );

    @WebResult(name = "CreateQDN_GenericResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateQDN_Generic", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateQDNGeneric")
    @WebMethod(operationName = "CreateQDN_Generic", action = "http://tempuri.org/CreateQDN_Generic")
    @ResponseWrapper(localName = "CreateQDN_GenericResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateQDNGenericResponse")
    public java.lang.String createQDNGeneric(
        @WebParam(name = "ThisQDN", targetNamespace = "http://tempuri.org/")
        org.tempuri.QDNAttributesGeneric thisQDN
    );

    @WebResult(name = "PrintMiniUnitLabelForSSDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PrintMiniUnitLabelForSSD", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PrintMiniUnitLabelForSSD")
    @WebMethod(operationName = "PrintMiniUnitLabelForSSD", action = "http://tempuri.org/PrintMiniUnitLabelForSSD")
    @ResponseWrapper(localName = "PrintMiniUnitLabelForSSDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PrintMiniUnitLabelForSSDResponse")
    public java.lang.String printMiniUnitLabelForSSD(
        @WebParam(name = "WorkOrder", targetNamespace = "http://tempuri.org/")
        java.lang.String workOrder,
        @WebParam(name = "StartPos", targetNamespace = "http://tempuri.org/")
        long startPos,
        @WebParam(name = "EndPos", targetNamespace = "http://tempuri.org/")
        long endPos,
        @WebParam(name = "PrinterName", targetNamespace = "http://tempuri.org/")
        java.lang.String printerName
    );

    @WebResult(name = "PrintDefectLabelForSSDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PrintDefectLabelForSSD", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PrintDefectLabelForSSD")
    @WebMethod(operationName = "PrintDefectLabelForSSD", action = "http://tempuri.org/PrintDefectLabelForSSD")
    @ResponseWrapper(localName = "PrintDefectLabelForSSDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PrintDefectLabelForSSDResponse")
    public java.lang.String printDefectLabelForSSD(
        @WebParam(name = "SerialNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String serialNumber,
        @WebParam(name = "PrinterName", targetNamespace = "http://tempuri.org/")
        java.lang.String printerName
    );

    @WebResult(name = "QDN_TestErrorProofReloadMesDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "QDN_TestErrorProofReloadMesData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QDNTestErrorProofReloadMesData")
    @WebMethod(operationName = "QDN_TestErrorProofReloadMesData", action = "http://tempuri.org/QDN_TestErrorProofReloadMesData")
    @ResponseWrapper(localName = "QDN_TestErrorProofReloadMesDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QDNTestErrorProofReloadMesDataResponse")
    public java.lang.String qdnTestErrorProofReloadMesData(
        @WebParam(name = "SQNum", targetNamespace = "http://tempuri.org/")
        java.lang.String sqNum
    );

    @WebResult(name = "TrackOutLotResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TrackOutLot", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TrackOutLot")
    @WebMethod(operationName = "TrackOutLot", action = "http://tempuri.org/TrackOutLot")
    @ResponseWrapper(localName = "TrackOutLotResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TrackOutLotResponse")
    public java.lang.String trackOutLot(
        @WebParam(name = "LotNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String lotNumber,
        @WebParam(name = "EquipmentID", targetNamespace = "http://tempuri.org/")
        java.lang.String equipmentID,
        @WebParam(name = "TrackOutQty", targetNamespace = "http://tempuri.org/")
        java.lang.String trackOutQty
    );

    @WebResult(name = "ProcessRejectTransactionForSSDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ProcessRejectTransactionForSSD", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcessRejectTransactionForSSD")
    @WebMethod(operationName = "ProcessRejectTransactionForSSD", action = "http://tempuri.org/ProcessRejectTransactionForSSD")
    @ResponseWrapper(localName = "ProcessRejectTransactionForSSDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcessRejectTransactionForSSDResponse")
    public java.lang.String processRejectTransactionForSSD(
        @WebParam(name = "WorkOrder", targetNamespace = "http://tempuri.org/")
        java.lang.String workOrder,
        @WebParam(name = "SerialNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String serialNumber,
        @WebParam(name = "RejectCode", targetNamespace = "http://tempuri.org/")
        java.lang.String rejectCode,
        @WebParam(name = "LogonUser", targetNamespace = "http://tempuri.org/")
        java.lang.String logonUser
    );

    @WebResult(name = "CreateQDN_TEPResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateQDN_TEP", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateQDNTEP")
    @WebMethod(operationName = "CreateQDN_TEP", action = "http://tempuri.org/CreateQDN_TEP")
    @ResponseWrapper(localName = "CreateQDN_TEPResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateQDNTEPResponse")
    public java.lang.String createQDNTEP(
        @WebParam(name = "ThisQDN", targetNamespace = "http://tempuri.org/")
        org.tempuri.QDNAttributesTEP thisQDN
    );

    @WebResult(name = "getSpasVisitingGuestListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getSpasVisitingGuestList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSpasVisitingGuestList")
    @WebMethod(action = "http://tempuri.org/getSpasVisitingGuestList")
    @ResponseWrapper(localName = "getSpasVisitingGuestListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSpasVisitingGuestListResponse")
    public java.lang.String getSpasVisitingGuestList(
        @WebParam(name = "Escort", targetNamespace = "http://tempuri.org/")
        java.lang.String escort
    );

    @WebResult(name = "getStatusAboutWorkOrderMaterialVerificationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getStatusAboutWorkOrderMaterialVerification", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStatusAboutWorkOrderMaterialVerification")
    @WebMethod(action = "http://tempuri.org/getStatusAboutWorkOrderMaterialVerification")
    @ResponseWrapper(localName = "getStatusAboutWorkOrderMaterialVerificationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStatusAboutWorkOrderMaterialVerificationResponse")
    public java.lang.String getStatusAboutWorkOrderMaterialVerification(
        @WebParam(name = "WorkOrder", targetNamespace = "http://tempuri.org/")
        java.lang.String workOrder
    );

    @WebResult(name = "CheckTestResultForSSDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckTestResultForSSD", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckTestResultForSSD")
    @WebMethod(operationName = "CheckTestResultForSSD", action = "http://tempuri.org/CheckTestResultForSSD")
    @ResponseWrapper(localName = "CheckTestResultForSSDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckTestResultForSSDResponse")
    public java.lang.String checkTestResultForSSD(
        @WebParam(name = "UnitID", targetNamespace = "http://tempuri.org/")
        java.lang.String unitID,
        @WebParam(name = "TrackInTime", targetNamespace = "http://tempuri.org/")
        java.lang.String trackInTime,
        @WebParam(name = "TestOperationName", targetNamespace = "http://tempuri.org/")
        java.lang.String testOperationName
    );

    @WebResult(name = "LotRejectInputResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "LotRejectInput", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LotRejectInput")
    @WebMethod(operationName = "LotRejectInput", action = "http://tempuri.org/LotRejectInput")
    @ResponseWrapper(localName = "LotRejectInputResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.LotRejectInputResponse")
    public java.lang.String lotRejectInput(
        @WebParam(name = "LotNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String lotNumber,
        @WebParam(name = "EquipmentID", targetNamespace = "http://tempuri.org/")
        java.lang.String equipmentID,
        @WebParam(name = "RejectCode", targetNamespace = "http://tempuri.org/")
        java.lang.String rejectCode,
        @WebParam(name = "RejectQTY", targetNamespace = "http://tempuri.org/")
        long rejectQTY
    );

    @WebResult(name = "SetWorkOrderAttributesResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SetWorkOrderAttributes", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetWorkOrderAttributes")
    @WebMethod(operationName = "SetWorkOrderAttributes", action = "http://tempuri.org/SetWorkOrderAttributes")
    @ResponseWrapper(localName = "SetWorkOrderAttributesResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetWorkOrderAttributesResponse")
    public java.lang.String setWorkOrderAttributes(
        @WebParam(name = "WO", targetNamespace = "http://tempuri.org/")
        java.lang.String wo
    );

    @RequestWrapper(localName = "SaveMail", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveMail")
    @WebMethod(operationName = "SaveMail", action = "http://tempuri.org/SaveMail")
    @ResponseWrapper(localName = "SaveMailResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SaveMailResponse")
    public void saveMail(
        @WebParam(name = "strSubject", targetNamespace = "http://tempuri.org/")
        java.lang.String strSubject,
        @WebParam(name = "EmailIDs", targetNamespace = "http://tempuri.org/")
        java.lang.String emailIDs,
        @WebParam(name = "MailBody", targetNamespace = "http://tempuri.org/")
        java.lang.String mailBody,
        @WebParam(name = "EmailCCs", targetNamespace = "http://tempuri.org/")
        java.lang.String emailCCs,
        @WebParam(name = "PriorityCode", targetNamespace = "http://tempuri.org/")
        long priorityCode
    );

    @WebResult(name = "ServiceTestingResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ServiceTesting", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ServiceTesting")
    @WebMethod(operationName = "ServiceTesting", action = "http://tempuri.org/ServiceTesting")
    @ResponseWrapper(localName = "ServiceTestingResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ServiceTestingResponse")
    public java.lang.String serviceTesting(
        @WebParam(name = "InputString", targetNamespace = "http://tempuri.org/")
        java.lang.String inputString
    );

    @WebResult(name = "getLotRejectQTYResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getLotRejectQTY", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLotRejectQTY")
    @WebMethod(action = "http://tempuri.org/getLotRejectQTY")
    @ResponseWrapper(localName = "getLotRejectQTYResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetLotRejectQTYResponse")
    public long getLotRejectQTY(
        @WebParam(name = "LotNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String lotNumber,
        @WebParam(name = "RejectCodes", targetNamespace = "http://tempuri.org/")
        java.lang.String rejectCodes
    );

    @WebResult(name = "MoveOutLotResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MoveOutLot", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MoveOutLot")
    @WebMethod(operationName = "MoveOutLot", action = "http://tempuri.org/MoveOutLot")
    @ResponseWrapper(localName = "MoveOutLotResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MoveOutLotResponse")
    public java.lang.String moveOutLot(
        @WebParam(name = "LotNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String lotNumber
    );

    @WebResult(name = "ModifyLotAttributeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ModifyLotAttribute", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ModifyLotAttribute")
    @WebMethod(operationName = "ModifyLotAttribute", action = "http://tempuri.org/ModifyLotAttribute")
    @ResponseWrapper(localName = "ModifyLotAttributeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ModifyLotAttributeResponse")
    public java.lang.String modifyLotAttribute(
        @WebParam(name = "LotNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String lotNumber,
        @WebParam(name = "AttributeName", targetNamespace = "http://tempuri.org/")
        java.lang.String attributeName,
        @WebParam(name = "AttributeValue", targetNamespace = "http://tempuri.org/")
        java.lang.String attributeValue,
        @WebParam(name = "TheComment", targetNamespace = "http://tempuri.org/")
        java.lang.String theComment
    );

    @WebResult(name = "MoveWholeBoxForSSDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MoveWholeBoxForSSD", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MoveWholeBoxForSSD")
    @WebMethod(operationName = "MoveWholeBoxForSSD", action = "http://tempuri.org/MoveWholeBoxForSSD")
    @ResponseWrapper(localName = "MoveWholeBoxForSSDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.MoveWholeBoxForSSDResponse")
    public java.lang.String moveWholeBoxForSSD(
        @WebParam(name = "BoxID", targetNamespace = "http://tempuri.org/")
        java.lang.String boxID,
        @WebParam(name = "UserID", targetNamespace = "http://tempuri.org/")
        java.lang.String userID,
        @WebParam(name = "CimStepCode", targetNamespace = "http://tempuri.org/")
        java.lang.String cimStepCode
    );

    @WebResult(name = "CreateQDN_ALYResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateQDN_ALY", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateQDNALY")
    @WebMethod(operationName = "CreateQDN_ALY", action = "http://tempuri.org/CreateQDN_ALY")
    @ResponseWrapper(localName = "CreateQDN_ALYResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateQDNALYResponse")
    public java.lang.String createQDNALY(
        @WebParam(name = "ThisQDN", targetNamespace = "http://tempuri.org/")
        org.tempuri.QDNAttributesALY thisQDN
    );

    @WebResult(name = "CreateQDN_TLYResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CreateQDN_TLY", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateQDNTLY")
    @WebMethod(operationName = "CreateQDN_TLY", action = "http://tempuri.org/CreateQDN_TLY")
    @ResponseWrapper(localName = "CreateQDN_TLYResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateQDNTLYResponse")
    public java.lang.String createQDNTLY(
        @WebParam(name = "ThisQDN", targetNamespace = "http://tempuri.org/")
        org.tempuri.QDNAttributesTLY thisQDN
    );

    @WebResult(name = "PrintMainLabelForSSDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PrintMainLabelForSSD", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PrintMainLabelForSSD")
    @WebMethod(operationName = "PrintMainLabelForSSD", action = "http://tempuri.org/PrintMainLabelForSSD")
    @ResponseWrapper(localName = "PrintMainLabelForSSDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PrintMainLabelForSSDResponse")
    public java.lang.String printMainLabelForSSD(
        @WebParam(name = "ThisSSDUnit", targetNamespace = "http://tempuri.org/")
        org.tempuri.SSDMainLabelParameters thisSSDUnit
    );
}
