package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2014-01-06T13:27:11.024+08:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "Service1Soap")
@XmlSeeAlso({ObjectFactory.class})
public interface Service1Soap {

    @WebResult(name = "getSpasVisitingGuestListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getSpasVisitingGuestList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSpasVisitingGuestList")
    @WebMethod(action = "http://tempuri.org/getSpasVisitingGuestList")
    @ResponseWrapper(localName = "getSpasVisitingGuestListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSpasVisitingGuestListResponse")
    public java.lang.String getSpasVisitingGuestList(
        @WebParam(name = "Escort", targetNamespace = "http://tempuri.org/")
        java.lang.String escort
    );
}
