
package org.tempuri;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2014-01-06T13:27:10.934+08:00
 * Generated source version: 2.7.5
 * 
 */
public final class Service1Soap_Service1Soap12_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "Service1");

    private Service1Soap_Service1Soap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Service1.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Service1 ss = new Service1(wsdlURL, SERVICE_NAME);
        Service1Soap port = ss.getService1Soap12();  
        
        {
        System.out.println("Invoking printPanelLabelForSSD...");
        java.lang.String _printPanelLabelForSSD_workOrder = "";
        long _printPanelLabelForSSD_startPos = 0;
        long _printPanelLabelForSSD_endPos = 0;
        java.lang.String _printPanelLabelForSSD_printerName = "";
        java.lang.String _printPanelLabelForSSD__return = port.printPanelLabelForSSD(_printPanelLabelForSSD_workOrder, _printPanelLabelForSSD_startPos, _printPanelLabelForSSD_endPos, _printPanelLabelForSSD_printerName);
        System.out.println("printPanelLabelForSSD.result=" + _printPanelLabelForSSD__return);


        }
        {
        System.out.println("Invoking getSpasUserAttributes...");
        java.lang.String _getSpasUserAttributes_badgeID = "";
        java.lang.String _getSpasUserAttributes__return = port.getSpasUserAttributes(_getSpasUserAttributes_badgeID);
        System.out.println("getSpasUserAttributes.result=" + _getSpasUserAttributes__return);


        }
        {
        System.out.println("Invoking spasUserPasswordValidation...");
        java.lang.String _spasUserPasswordValidation_badgeID = "";
        java.lang.String _spasUserPasswordValidation_password = "";
        java.lang.String _spasUserPasswordValidation__return = port.spasUserPasswordValidation(_spasUserPasswordValidation_badgeID, _spasUserPasswordValidation_password);
        System.out.println("spasUserPasswordValidation.result=" + _spasUserPasswordValidation__return);


        }
        {
        System.out.println("Invoking obaLabelCheckForSSD...");
        java.lang.String _obaLabelCheckForSSD_scanningString = "";
        java.lang.String _obaLabelCheckForSSD_userID = "";
        java.lang.String _obaLabelCheckForSSD_lineID = "";
        java.lang.String _obaLabelCheckForSSD_cimStepCode = "";
        java.lang.String _obaLabelCheckForSSD__return = port.obaLabelCheckForSSD(_obaLabelCheckForSSD_scanningString, _obaLabelCheckForSSD_userID, _obaLabelCheckForSSD_lineID, _obaLabelCheckForSSD_cimStepCode);
        System.out.println("obaLabelCheckForSSD.result=" + _obaLabelCheckForSSD__return);


        }
        {
        System.out.println("Invoking createQDNSPC...");
        org.tempuri.QDNAttributesSPC _createQDNSPC_thisQDN = null;
        java.lang.String _createQDNSPC__return = port.createQDNSPC(_createQDNSPC_thisQDN);
        System.out.println("createQDNSPC.result=" + _createQDNSPC__return);


        }
        {
        System.out.println("Invoking lotRelease...");
        java.lang.String _lotRelease_lotNumber = "";
        java.lang.String _lotRelease_reasonCode = "";
        java.lang.String _lotRelease_comments = "";
        java.lang.String _lotRelease__return = port.lotRelease(_lotRelease_lotNumber, _lotRelease_reasonCode, _lotRelease_comments);
        System.out.println("lotRelease.result=" + _lotRelease__return);


        }
        {
        System.out.println("Invoking createQDNGeneric...");
        org.tempuri.QDNAttributesGeneric _createQDNGeneric_thisQDN = null;
        java.lang.String _createQDNGeneric__return = port.createQDNGeneric(_createQDNGeneric_thisQDN);
        System.out.println("createQDNGeneric.result=" + _createQDNGeneric__return);


        }
        {
        System.out.println("Invoking printMiniUnitLabelForSSD...");
        java.lang.String _printMiniUnitLabelForSSD_workOrder = "";
        long _printMiniUnitLabelForSSD_startPos = 0;
        long _printMiniUnitLabelForSSD_endPos = 0;
        java.lang.String _printMiniUnitLabelForSSD_printerName = "";
        java.lang.String _printMiniUnitLabelForSSD__return = port.printMiniUnitLabelForSSD(_printMiniUnitLabelForSSD_workOrder, _printMiniUnitLabelForSSD_startPos, _printMiniUnitLabelForSSD_endPos, _printMiniUnitLabelForSSD_printerName);
        System.out.println("printMiniUnitLabelForSSD.result=" + _printMiniUnitLabelForSSD__return);


        }
        {
        System.out.println("Invoking printDefectLabelForSSD...");
        java.lang.String _printDefectLabelForSSD_serialNumber = "";
        java.lang.String _printDefectLabelForSSD_printerName = "";
        java.lang.String _printDefectLabelForSSD__return = port.printDefectLabelForSSD(_printDefectLabelForSSD_serialNumber, _printDefectLabelForSSD_printerName);
        System.out.println("printDefectLabelForSSD.result=" + _printDefectLabelForSSD__return);


        }
        {
        System.out.println("Invoking qdnTestErrorProofReloadMesData...");
        java.lang.String _qdnTestErrorProofReloadMesData_sqNum = "";
        java.lang.String _qdnTestErrorProofReloadMesData__return = port.qdnTestErrorProofReloadMesData(_qdnTestErrorProofReloadMesData_sqNum);
        System.out.println("qdnTestErrorProofReloadMesData.result=" + _qdnTestErrorProofReloadMesData__return);


        }
        {
        System.out.println("Invoking trackOutLot...");
        java.lang.String _trackOutLot_lotNumber = "";
        java.lang.String _trackOutLot_equipmentID = "";
        java.lang.String _trackOutLot_trackOutQty = "";
        java.lang.String _trackOutLot__return = port.trackOutLot(_trackOutLot_lotNumber, _trackOutLot_equipmentID, _trackOutLot_trackOutQty);
        System.out.println("trackOutLot.result=" + _trackOutLot__return);


        }
        {
        System.out.println("Invoking processRejectTransactionForSSD...");
        java.lang.String _processRejectTransactionForSSD_workOrder = "";
        java.lang.String _processRejectTransactionForSSD_serialNumber = "";
        java.lang.String _processRejectTransactionForSSD_rejectCode = "";
        java.lang.String _processRejectTransactionForSSD_logonUser = "";
        java.lang.String _processRejectTransactionForSSD__return = port.processRejectTransactionForSSD(_processRejectTransactionForSSD_workOrder, _processRejectTransactionForSSD_serialNumber, _processRejectTransactionForSSD_rejectCode, _processRejectTransactionForSSD_logonUser);
        System.out.println("processRejectTransactionForSSD.result=" + _processRejectTransactionForSSD__return);


        }
        {
        System.out.println("Invoking createQDNTEP...");
        org.tempuri.QDNAttributesTEP _createQDNTEP_thisQDN = null;
        java.lang.String _createQDNTEP__return = port.createQDNTEP(_createQDNTEP_thisQDN);
        System.out.println("createQDNTEP.result=" + _createQDNTEP__return);


        }
        {
        System.out.println("Invoking getSpasVisitingGuestList...");
        java.lang.String _getSpasVisitingGuestList_escort = "";
        java.lang.String _getSpasVisitingGuestList__return = port.getSpasVisitingGuestList(_getSpasVisitingGuestList_escort);
        System.out.println("getSpasVisitingGuestList.result=" + _getSpasVisitingGuestList__return);


        }
        {
        System.out.println("Invoking getStatusAboutWorkOrderMaterialVerification...");
        java.lang.String _getStatusAboutWorkOrderMaterialVerification_workOrder = "";
        java.lang.String _getStatusAboutWorkOrderMaterialVerification__return = port.getStatusAboutWorkOrderMaterialVerification(_getStatusAboutWorkOrderMaterialVerification_workOrder);
        System.out.println("getStatusAboutWorkOrderMaterialVerification.result=" + _getStatusAboutWorkOrderMaterialVerification__return);


        }
        {
        System.out.println("Invoking checkTestResultForSSD...");
        java.lang.String _checkTestResultForSSD_unitID = "";
        java.lang.String _checkTestResultForSSD_trackInTime = "";
        java.lang.String _checkTestResultForSSD_testOperationName = "";
        java.lang.String _checkTestResultForSSD__return = port.checkTestResultForSSD(_checkTestResultForSSD_unitID, _checkTestResultForSSD_trackInTime, _checkTestResultForSSD_testOperationName);
        System.out.println("checkTestResultForSSD.result=" + _checkTestResultForSSD__return);


        }
        {
        System.out.println("Invoking lotRejectInput...");
        java.lang.String _lotRejectInput_lotNumber = "";
        java.lang.String _lotRejectInput_equipmentID = "";
        java.lang.String _lotRejectInput_rejectCode = "";
        long _lotRejectInput_rejectQTY = 0;
        java.lang.String _lotRejectInput__return = port.lotRejectInput(_lotRejectInput_lotNumber, _lotRejectInput_equipmentID, _lotRejectInput_rejectCode, _lotRejectInput_rejectQTY);
        System.out.println("lotRejectInput.result=" + _lotRejectInput__return);


        }
        {
        System.out.println("Invoking setWorkOrderAttributes...");
        java.lang.String _setWorkOrderAttributes_wo = "";
        java.lang.String _setWorkOrderAttributes__return = port.setWorkOrderAttributes(_setWorkOrderAttributes_wo);
        System.out.println("setWorkOrderAttributes.result=" + _setWorkOrderAttributes__return);


        }
        {
        System.out.println("Invoking saveMail...");
        java.lang.String _saveMail_strSubject = "";
        java.lang.String _saveMail_emailIDs = "";
        java.lang.String _saveMail_mailBody = "";
        java.lang.String _saveMail_emailCCs = "";
        long _saveMail_priorityCode = 0;
        port.saveMail(_saveMail_strSubject, _saveMail_emailIDs, _saveMail_mailBody, _saveMail_emailCCs, _saveMail_priorityCode);


        }
        {
        System.out.println("Invoking serviceTesting...");
        java.lang.String _serviceTesting_inputString = "";
        java.lang.String _serviceTesting__return = port.serviceTesting(_serviceTesting_inputString);
        System.out.println("serviceTesting.result=" + _serviceTesting__return);


        }
        {
        System.out.println("Invoking getLotRejectQTY...");
        java.lang.String _getLotRejectQTY_lotNumber = "";
        java.lang.String _getLotRejectQTY_rejectCodes = "";
        long _getLotRejectQTY__return = port.getLotRejectQTY(_getLotRejectQTY_lotNumber, _getLotRejectQTY_rejectCodes);
        System.out.println("getLotRejectQTY.result=" + _getLotRejectQTY__return);


        }
        {
        System.out.println("Invoking moveOutLot...");
        java.lang.String _moveOutLot_lotNumber = "";
        java.lang.String _moveOutLot__return = port.moveOutLot(_moveOutLot_lotNumber);
        System.out.println("moveOutLot.result=" + _moveOutLot__return);


        }
        {
        System.out.println("Invoking modifyLotAttribute...");
        java.lang.String _modifyLotAttribute_lotNumber = "";
        java.lang.String _modifyLotAttribute_attributeName = "";
        java.lang.String _modifyLotAttribute_attributeValue = "";
        java.lang.String _modifyLotAttribute_theComment = "";
        java.lang.String _modifyLotAttribute__return = port.modifyLotAttribute(_modifyLotAttribute_lotNumber, _modifyLotAttribute_attributeName, _modifyLotAttribute_attributeValue, _modifyLotAttribute_theComment);
        System.out.println("modifyLotAttribute.result=" + _modifyLotAttribute__return);


        }
        {
        System.out.println("Invoking moveWholeBoxForSSD...");
        java.lang.String _moveWholeBoxForSSD_boxID = "";
        java.lang.String _moveWholeBoxForSSD_userID = "";
        java.lang.String _moveWholeBoxForSSD_cimStepCode = "";
        java.lang.String _moveWholeBoxForSSD__return = port.moveWholeBoxForSSD(_moveWholeBoxForSSD_boxID, _moveWholeBoxForSSD_userID, _moveWholeBoxForSSD_cimStepCode);
        System.out.println("moveWholeBoxForSSD.result=" + _moveWholeBoxForSSD__return);


        }
        {
        System.out.println("Invoking createQDNALY...");
        org.tempuri.QDNAttributesALY _createQDNALY_thisQDN = null;
        java.lang.String _createQDNALY__return = port.createQDNALY(_createQDNALY_thisQDN);
        System.out.println("createQDNALY.result=" + _createQDNALY__return);


        }
        {
        System.out.println("Invoking createQDNTLY...");
        org.tempuri.QDNAttributesTLY _createQDNTLY_thisQDN = null;
        java.lang.String _createQDNTLY__return = port.createQDNTLY(_createQDNTLY_thisQDN);
        System.out.println("createQDNTLY.result=" + _createQDNTLY__return);


        }
        {
        System.out.println("Invoking printMainLabelForSSD...");
        org.tempuri.SSDMainLabelParameters _printMainLabelForSSD_thisSSDUnit = null;
        java.lang.String _printMainLabelForSSD__return = port.printMainLabelForSSD(_printMainLabelForSSD_thisSSDUnit);
        System.out.println("printMainLabelForSSD.result=" + _printMainLabelForSSD__return);


        }

        System.exit(0);
    }

}
